spring:
  ai:
    openai:
      enabled: false # désactive OpenAiChatModel auto-configuré

  application:
    name: ms-crypto-chatBot

  datasource:
    url: jdbc:h2:mem:chatbotdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret: "xzUJZImXQvFJIrrVTa7wKF1mt9c3pnv0O4gx4YOrZtxuCEs2CwTWEL3nTJSZrjDQGLblkeGGVIKbeaaXd03II4Ejo2gKVJDk7SIn"
  expiration: 3600000  # Exemple: 1 heure (en ms)
ms:
  crypto:
    url: http://ms-crypto:8080 # URL de votre service crypto existant
server:
  port: 8888
