spring:
  application:
    name: ms-crypto-alerts

  mail:
    host: smtp.gmail.com
    port: 587
    username: ton.email@gmail.com
    password: tonMotDePasseOuAppPassword
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9999

jwt:
  secret: "xzUJZImXQvFJIrrVTa7wKF1mt9c3pnv0O4gx4YOrZtxuCEs2CwTWEL3nTJSZrjDQGLblkeGGVIKbeaaXd03II4Ejo2gKVJDk7SIn"
  expiration: 3600000  # 1 heure en millisecondes
